apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/timpan4/guestbook
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - git:
      repoURL: https://github.com/timpan4/kargo-advanced.git
      branch: main
